const express = require('express');
const router = express.Router();
const axios = require('axios');
const { Project } = require('../models');
const { authenticateToken } = require('../middleware/auth');
const { asyncHandler, APIError } = require('../middleware/errorHandler');

/**
 * @route   POST /api/github/export/:projectId
 * @desc    Export project to GitHub repository
 * @access  Private
 */
router.post(
  '/export/:projectId',
  authenticateToken,
  asyncHandler(async (req, res) => {
    const { repoName, description, isPrivate = false, githubToken } = req.body;

    if (!repoName || !githubToken) {
      throw new APIError('Repository name and GitHub token are required', 400);
    }

    // Get project
    const project = await Project.findById(req.params.projectId);

    if (!project) {
      throw new APIError('Project not found', 404);
    }

    // Check permission
    if (project.owner.toString() !== req.user._id.toString()) {
      throw new APIError('Only the project owner can export to GitHub', 403);
    }

    try {
      // 1. Create GitHub repository
      const createRepoResponse = await axios.post(
        'https://api.github.com/user/repos',
        {
          name: repoName,
          description: description || project.description || 'Generated by AI Builder',
          private: isPrivate,
          auto_init: true, // Initialize with README
        },
        {
          headers: {
            Authorization: `token ${githubToken}`,
            Accept: 'application/vnd.github.v3+json',
          },
        }
      );

      const repo = createRepoResponse.data;

      // 2. Prepare files to commit
      const files = [];

      // Component JSX file
      if (project.code.jsx) {
        files.push({
          path: 'src/Component.jsx',
          content: project.code.jsx,
        });
      }

      // HTML file
      if (project.code.html) {
        files.push({
          path: 'public/index.html',
          content: project.code.html,
        });
      }

      // CSS file
      if (project.code.css) {
        files.push({
          path: 'src/styles.css',
          content: project.code.css,
        });
      }

      // JavaScript file
      if (project.code.js) {
        files.push({
          path: 'src/script.js',
          content: project.code.js,
        });
      }

      // README
      files.push({
        path: 'README.md',
        content: generateReadme(project),
      });

      // package.json
      files.push({
        path: 'package.json',
        content: JSON.stringify(
          {
            name: repoName,
            version: '1.0.0',
            description: description || project.description,
            scripts: {
              dev: 'vite',
              build: 'vite build',
              preview: 'vite preview',
            },
            dependencies: {
              react: '^18.2.0',
              'react-dom': '^18.2.0',
            },
            devDependencies: {
              '@vitejs/plugin-react': '^4.0.0',
              autoprefixer: '^10.4.14',
              postcss: '^8.4.24',
              tailwindcss: '^3.3.2',
              vite: '^4.3.9',
            },
          },
          null,
          2
        ),
      });

      // 3. Get the default branch's latest commit
      const branchResponse = await axios.get(
        `https://api.github.com/repos/${repo.owner.login}/${repo.name}/git/refs/heads/${repo.default_branch}`,
        {
          headers: {
            Authorization: `token ${githubToken}`,
            Accept: 'application/vnd.github.v3+json',
          },
        }
      );

      const latestCommitSha = branchResponse.data.object.sha;

      // 4. Create blobs for each file
      const blobs = await Promise.all(
        files.map(async (file) => {
          const blobResponse = await axios.post(
            `https://api.github.com/repos/${repo.owner.login}/${repo.name}/git/blobs`,
            {
              content: Buffer.from(file.content).toString('base64'),
              encoding: 'base64',
            },
            {
              headers: {
                Authorization: `token ${githubToken}`,
                Accept: 'application/vnd.github.v3+json',
              },
            }
          );
          return {
            path: file.path,
            mode: '100644',
            type: 'blob',
            sha: blobResponse.data.sha,
          };
        })
      );

      // 5. Create tree
      const treeResponse = await axios.post(
        `https://api.github.com/repos/${repo.owner.login}/${repo.name}/git/trees`,
        {
          base_tree: latestCommitSha,
          tree: blobs,
        },
        {
          headers: {
            Authorization: `token ${githubToken}`,
            Accept: 'application/vnd.github.v3+json',
          },
        }
      );

      // 6. Create commit
      const commitResponse = await axios.post(
        `https://api.github.com/repos/${repo.owner.login}/${repo.name}/git/commits`,
        {
          message: 'Initial commit from AI Builder',
          tree: treeResponse.data.sha,
          parents: [latestCommitSha],
        },
        {
          headers: {
            Authorization: `token ${githubToken}`,
            Accept: 'application/vnd.github.v3+json',
          },
        }
      );

      // 7. Update reference
      await axios.patch(
        `https://api.github.com/repos/${repo.owner.login}/${repo.name}/git/refs/heads/${repo.default_branch}`,
        {
          sha: commitResponse.data.sha,
        },
        {
          headers: {
            Authorization: `token ${githubToken}`,
            Accept: 'application/vnd.github.v3+json',
          },
        }
      );

      // 8. Update project with GitHub info
      project.githubRepo = {
        url: repo.html_url,
        branch: repo.default_branch,
        exportedAt: new Date(),
      };
      await project.save();

      res.json({
        success: true,
        message: 'Project exported to GitHub successfully',
        data: {
          repoUrl: repo.html_url,
          cloneUrl: repo.clone_url,
        },
      });
    } catch (error) {
      // Handle GitHub API errors
      if (error.response) {
        const status = error.response.status;
        const message = error.response.data.message;

        if (status === 401) {
          throw new APIError('Invalid GitHub token', 401);
        }
        if (status === 422 && message.includes('already exists')) {
          throw new APIError('Repository name already exists', 400);
        }
        throw new APIError(`GitHub API error: ${message}`, status);
      }

      throw new APIError('Failed to export to GitHub', 500);
    }
  })
);

/**
 * Helper function to generate README content
 */
function generateReadme(project) {
  return `# ${project.name}

${project.description || 'Generated with AI Builder'}

## 🚀 About This Project

This project was created using **AI Builder** - an AI-powered UI generation tool.

## 📦 Installation

\`\`\`bash
npm install
\`\`\`

## 🏃 Running the Project

\`\`\`bash
npm run dev
\`\`\`

## 🛠️ Built With

- React
- Tailwind CSS
- Vite

## 📝 Project Details

- **Created**: ${new Date(project.createdAt).toLocaleDateString()}
- **Last Updated**: ${new Date(project.updatedAt).toLocaleDateString()}
- **Versions**: ${project.versions.length}

## 📄 License

This project is open source and available under the MIT License.
`;
}

/**
 * @route   GET /api/github/user
 * @desc    Get GitHub user info
 * @access  Private
 */
router.get(
  '/user',
  authenticateToken,
  asyncHandler(async (req, res) => {
    const { githubToken } = req.query;

    if (!githubToken) {
      throw new APIError('GitHub token is required', 400);
    }

    try {
      const response = await axios.get('https://api.github.com/user', {
        headers: {
          Authorization: `token ${githubToken}`,
          Accept: 'application/vnd.github.v3+json',
        },
      });

      res.json({
        success: true,
        data: {
          username: response.data.login,
          name: response.data.name,
          avatar: response.data.avatar_url,
          publicRepos: response.data.public_repos,
        },
      });
    } catch (error) {
      if (error.response && error.response.status === 401) {
        throw new APIError('Invalid GitHub token', 401);
      }
      throw new APIError('Failed to fetch GitHub user', 500);
    }
  })
);

module.exports = router;
